plugins {
    alias(libs.plugins.unimined) apply false
    alias(libs.plugins.shadow) apply false
}

allprojects {
    group = "${mod_package}"
    version = "${mod_version}"
}

subprojects {
    pluginManager.withPlugin('java') {
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(findProperty('java_version') as String)
            }
        }

        repositories {
            mavenCentral()
        }

        tasks.withType(JavaCompile).configureEach {
            options.encoding = 'UTF-8'
            options.release = (findProperty('java_version') as String).toInteger()
        }
    }

    pluginManager.withPlugin('com.gradleup.shadow') {
        evaluationDependsOn(':core')

        configurations {
            embed
            implementation.extendsFrom(embed)
        }

        dependencies {
            embed libs.jackson.databind
        }

        shadow {
            addShadowJarToAssembleLifecycle = false
        }

        tasks.named('jar').configure {
            enabled = false
        }

        def embedConfig = configurations.embed
        shadowJar {
            from { project(':core').sourceSets.main.output }
            configurations.set([embedConfig])
            enableAutoRelocation = true
            relocationPrefix = "${mod_package}.${mod_id}.repack"
            destinationDirectory = layout.buildDirectory.dir('tmp')
            archiveClassifier = ''
        }

        tasks.matching { it.name == 'remapShadowJar' }.configureEach {
            destinationDirectory = rootProject.layout.buildDirectory.dir('libs')
            archiveClassifier = ''
        }

        tasks.named('build') {
            dependsOn tasks.matching { it.name == 'remapShadowJar' }
        }

        tasks.named('processResources').configure {
            def props = [
                    mod_id         : findProperty('mod_id'),
                    mod_name       : findProperty('mod_name'),
                    mod_version    : findProperty('mod_version'),
                    mod_description: findProperty('mod_description'),
                    mod_authors    : findProperty('mod_authors'),
                    mod_url        : findProperty('mod_url'),
                    mod_logo_path  : findProperty('mod_logo_path'),
            ]
            inputs.properties props
            filesMatching(['META-INF/mods.toml', 'mcmod.info']) {
                expand props
            }
        }
    }
}
