plugins {
    id 'com.gradleup.shadow' version '9.5.1' apply false
    id 'com.diffplug.spotless' version '8.9.0' apply false
}

allprojects {
    group = "${mod_package}"
    version = "${mod_version}"
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'java-library'
    apply plugin: 'com.diffplug.spotless'

    def localPropFile = file("$projectDir/gradle.properties")
    if (localPropFile.exists()) {
        def localProps = new Properties()
        localPropFile.withInputStream { localProps.load(it) }
        localProps.each { k, v -> ext.set(k as String, (v as String).trim()) }
    }

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = 'https://maven.wagyourtail.xyz/releases' }
        maven { url = 'https://maven.wagyourtail.xyz/snapshots' }
        maven { url = 'https://maven.arcseekers.com/releases' }
        maven {
            url = 'https://repo.spongepowered.org/maven'
            content {
                includeGroup 'org.spongepowered'
                includeGroupByRegex 'org\\.spongepowered.*'
            }
        }
    }

    dependencies {
        compileOnly 'org.projectlombok:lombok:1.18.38'
        annotationProcessor 'org.projectlombok:lombok:1.18.38'
        testCompileOnly 'org.projectlombok:lombok:1.18.38'
        testAnnotationProcessor 'org.projectlombok:lombok:1.18.38'
    }

    spotless {
        java {
            target 'src/*/java/**/*.java'
            googleJavaFormat('1.35.0')
            removeUnusedImports()
            trimTrailingWhitespace()
            endWithNewline()
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        dependsOn tasks.named('spotlessApply')
    }

    tasks.named('build').configure {
        dependsOn tasks.named('spotlessApply')
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }

    tasks.withType(Jar).configureEach {
        destinationDirectory.set(rootProject.layout.buildDirectory.dir('libs'))
    }
}
