org.gradle.jvmargs            = -Xmx4G --enable-native-access=ALL-UNNAMED
org.gradle.parallel           = true
org.gradle.caching            = true
org.gradle.logging.stacktrace = all

# Mod Information
# HIGHLY RECOMMEND complying with SemVer for mod_version: https://semver.org/
mod_version                   = 0.3.1
mod_version_type              = release
mod_package                   = team.terrafirmagrag
mod_id                        = splice
mod_name                      = Splice

# Mod Metadata (Optional)
mod_description               = Client-side runtime merge of split lang files (flat + lang/{locale}/** fragments).
mod_authors                   = TerraFirmaGreg Team
mod_url                       = https://github.com/TerraFirmaGreg-Team/Splice
mod_logo_path                 = logo.png


# Platform
# Build environment
java_version                  = 25
