plugins {
    id 'java'
    alias(libs.plugins.unimined)
    alias(libs.plugins.shadow)
}

base {
    archivesName = "${mod_name}-${mod_name_suffix}"
}

unimined {
    minecraft {
        version minecraft_version
        mappings {
            mcp('stable', '39-1.12')
        }
        cleanroom {
            loader loader_version
            accessTransformer 'src/main/resources/META-INF/accesstransformer.cfg'
        }
        combineWith ':core:main'
        defaultRemapJar = false
        remap(tasks.shadowJar)
    }
}

shadowJar {
    manifest {
        attributes 'ModType': 'CRL'
        attributes 'FMLAT': 'accesstransformer.cfg'
    }
}
