plugins {
    id 'java-library'
}

dependencies {
    implementation libs.jackson.databind
    compileOnly libs.log4j.api
    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
}

test {
    useJUnitPlatform()
}

tasks.named('jar').configure {
    enabled = false
}
